// <auto-generated />
using System;
using DnDSolutions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DnDSolutions.Data.Migrations
{
    [DbContext(typeof(DnDSolutionsDbContext))]
    [Migration("20200428140730_BidsTable")]
    partial class BidsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DnDSolutions.Data.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("DeliveryItemId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("DnDSolutions.Data.DeliveryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CollectionDateEarliest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CollectionDateLatest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDateEarliest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDateLatest")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DeliveryItem");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Photos.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryItemId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryItemId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("ComodityType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrailerType")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.ATV", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("ATV");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Cat", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("Cat_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAllVaccinations")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCarrier")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpecificNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnName("Cat_Weight")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId1");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Dog", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnName("Dog_Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnName("Dog_Count")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("Dog_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAllVaccinations")
                        .HasColumnName("Dog_HasAllVaccinations")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCarrier")
                        .HasColumnName("Dog_HasCarrier")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpecificNeeds")
                        .HasColumnName("Dog_HasSpecificNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Dog_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnName("Dog_Weight")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId2");

                    b.HasDiscriminator().HasValue("Dog");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Horse", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("Breed")
                        .HasColumnName("Horse_Breed")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnName("Horse_Count")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Horse_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnName("Horse_Weight")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId3");

                    b.HasDiscriminator().HasValue("Horse");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Livestock", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnName("Livestock_Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnName("Livestock_Count")
                        .HasColumnType("int");

                    b.Property<bool>("HasAllTags")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAllVaccinations")
                        .HasColumnName("Livestock_HasAllVaccinations")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpecificNeeds")
                        .HasColumnName("Livestock_HasSpecificNeeds")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInCorral")
                        .HasColumnType("bit");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId4");

                    b.HasDiscriminator().HasValue("Livestock");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Boat", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("Boat_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnName("Boat_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnTrailer")
                        .HasColumnType("bit");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("Boat_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnName("Boat_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("Boat_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnName("Boat_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("Boat_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnName("Boat_WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId5");

                    b.HasDiscriminator().HasValue("Boat");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Car", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnName("Car_Make")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Car_Model")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ServiceType")
                        .HasColumnName("Car_ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId6");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Freights.LessThanContainerLoad", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("HandlingUnit")
                        .HasColumnType("int");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("LessThanContainerLoad_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnName("LessThanContainerLoad_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("bit");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("LessThanContainerLoad_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnName("LessThanContainerLoad_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("LessThanContainerLoad_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("LessThanContainerLoad_Type")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnName("LessThanContainerLoad_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("LessThanContainerLoad_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnName("LessThanContainerLoad_WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId7");

                    b.HasDiscriminator().HasValue("LessThanContainerLoad");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HeavyVehicle", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("HeavyVehicle_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnTrailer")
                        .HasColumnName("HeavyVehicle_IsOnTrailer")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnName("HeavyVehicle_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("HeavyVehicle_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnedTrailerType")
                        .HasColumnType("int");

                    b.Property<int>("TrailerType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("HeavyVehicle_Type")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId8");

                    b.HasDiscriminator().HasValue("HeavyVehicle");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Art", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("Art_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnName("Art_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("Art_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnName("Art_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("Art_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnName("Art_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("Art_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Packaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialHandling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("Art_Type")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnName("Art_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("Art_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnName("Art_WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId9");

                    b.HasDiscriminator().HasValue("Art");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.HouseholdItem", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("HouseholdItem_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("HouseholdItem_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnName("HouseholdItem_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<bool>("IsCrated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPalletised")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStickable")
                        .HasColumnType("bit");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("HouseholdItem_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnName("HouseholdItem_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("HouseholdItem_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("HouseholdItem_Type")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnName("HouseholdItem_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("HouseholdItem_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnName("HouseholdItem_WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId10");

                    b.HasDiscriminator().HasValue("HouseholdItem");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Move", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("Move_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("Move_Type")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId11");

                    b.HasDiscriminator().HasValue("Move");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Office", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("CollectionFloor")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryFloor")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryTitle")
                        .IsRequired()
                        .HasColumnName("Office_DeliveryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCollectionFloorElevator")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDeliveryFloorElevator")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDisassemblyItems")
                        .HasColumnType("bit");

                    b.Property<bool>("HasReassemblyItems")
                        .HasColumnType("bit");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId12");

                    b.HasDiscriminator().HasValue("Office");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Piano", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("HorizontalType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOnCasters")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnName("Piano_Type")
                        .HasColumnType("int");

                    b.Property<int>("VerticalType")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId13");

                    b.HasDiscriminator().HasValue("Piano");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Motorcycle", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnName("Motorcycle_Make")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Motorcycle_Model")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ServiceType")
                        .HasColumnName("Motorcycle_ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnName("Motorcycle_State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnName("Motorcycle_Type")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId14");

                    b.HasDiscriminator().HasValue("Motorcycle");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.RecreationalVehicle", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<bool?>("CanBeDriven")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnName("RecreationalVehicle_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("RecreationalVehicle_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .IsRequired()
                        .HasColumnName("RecreationalVehicle_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("RecreationalVehicle_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .IsRequired()
                        .HasColumnName("RecreationalVehicle_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnName("RecreationalVehicle_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("RecreationalVehicle_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnName("RecreationalVehicle_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("RecreationalVehicle_Type")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnName("RecreationalVehicle_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("RecreationalVehicle_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .IsRequired()
                        .HasColumnName("RecreationalVehicle_WidthSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId15");

                    b.HasDiscriminator().HasValue("RecreationalVehicle");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Snowmobile", b =>
                {
                    b.HasBaseType("DnDSolutions.Data.DeliveryItem");

                    b.Property<int>("HeightFirstPart")
                        .HasColumnName("Snowmobile_HeightFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("HeightSecondPart")
                        .HasColumnName("Snowmobile_HeightSecondPart")
                        .HasColumnType("int");

                    b.Property<int>("LengthFirstPart")
                        .HasColumnName("Snowmobile_LengthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("LengthSecondPart")
                        .HasColumnName("Snowmobile_LengthSecondPart")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnName("Snowmobile_Make")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MeasurementUnit")
                        .HasColumnName("Snowmobile_MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Snowmobile_Model")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Weight")
                        .HasColumnName("Snowmobile_Weight")
                        .HasColumnType("int");

                    b.Property<int>("WidthFirstPart")
                        .HasColumnName("Snowmobile_WidthFirstPart")
                        .HasColumnType("int");

                    b.Property<int?>("WidthSecondPart")
                        .HasColumnName("Snowmobile_WidthSecondPart")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .HasName("IX_DeliveryItem_UserId16");

                    b.HasDiscriminator().HasValue("Snowmobile");
                });

            modelBuilder.Entity("DnDSolutions.Data.Bid", b =>
                {
                    b.HasOne("DnDSolutions.Data.DeliveryItem", "DeliveryItem")
                        .WithMany("Bids")
                        .HasForeignKey("DeliveryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Photos.Photo", b =>
                {
                    b.HasOne("DnDSolutions.Data.DeliveryItem", "DeliveryItem")
                        .WithMany("Photos")
                        .HasForeignKey("DeliveryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDSolutions.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.ATV", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("ATVs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Cat", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Cats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId1");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Dog", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId2");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Horse", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Horses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId3");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Animals.Livestock", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Livestock")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId4");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Boat", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Boats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId5");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Car", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId6");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Freights.LessThanContainerLoad", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("LessThanContainerLoads")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId7");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HeavyVehicle", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("HeavyVehicles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId8");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Art", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Arts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId9");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.HouseholdItem", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("HouseholdItems")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId10");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Move", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Moves")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId11");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Office", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Offices")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId12");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.HouseholdItemsAndMoves.Piano", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Pianos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId13");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Motorcycles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId14");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.RecreationalVehicle", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("RecreationalVehicles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId15");
                });

            modelBuilder.Entity("DnDSolutions.Data.Models.Snowmobile", b =>
                {
                    b.HasOne("DnDSolutions.Data.Models.User", "User")
                        .WithMany("Snowmobiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeliveryItem_AspNetUsers_UserId16");
                });
#pragma warning restore 612, 618
        }
    }
}
